version: '3'
services:
  php-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: php-api
    ports:
      - "9001:80"
    volumes:
      - ./api:/app
    restart: always
    networks:
      - mi-red

networks:
  mi-red:
    external: true