version: "3.9"

services:
  php-app-web:
    container_name: php-app-web
    build:
      context: ./app-web
      dockerfile: Dockerfile
    ports:
      - "9000:80"
    depends_on:
      - mysql-db
    networks:
      - mi-red
    volumes:
      - ./app-web:/app

  mysql-db:
    image: mysql:8.3.0
    command:  --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - mi-red

volumes:
  db-data:
    name: db-data

networks:
  mi-red:
    driver: bridge
    name: mi-red
